### ISSUE TITLE
Exception thrown on startup

### ISSUE THREAD

**Issue by theplatapi** [divhide/node-log-server#1]
I'm trying to run the server, but I get the following error

```
module.js:329
    throw err;
    ^

Error: Cannot find module 'collections/shim'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/log-server/node_modules/q/q.js:43:1)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)

```

**Comment by aetheon** [comment]
Hi @theplatapi, v1.1.0 was published containing dependencies updates.

**Comment by theplatapi** [comment]
Thank you for updating this!
